
import 'feature_module.dart';

/// All optional features enabled in this project.
///
/// Generated by `fst create` — edit to add or remove features.
const List<FeatureModule> enabledFeatures = [
  // fst:enabled-features — `fst add-feature` inserts new modules above this line
];




// fst:feature-module-classes — `fst add-feature` inserts new module classes above
